
py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    deps = [":epsilon",
        ":exploration",
    ],
    visibility = ["//diadem/agents:__pkg__"],
)

py_library(
    name = "epsilon",
    srcs = ["epsilon.py"],
    visibility = ["//diadem/agents:__pkg__"],
)

py_library(
    name = "exploration",
    srcs = ["exploration.py"],
    visibility = ["//diadem/agents:__pkg__"],
)
