py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    deps = [
        "//diadem/agents:__init__",
        "//diadem/common:__init__",
        "//diadem/datamanager:__init__",
        "//diadem/experiment:__init__",
        "//diadem/summary:__init__",
        "//diadem/environments:__init__",
        "//diadem/preprocessors:__init__",
    ],
    imports = ["."],
    visibility = ["//visibility:public"],
)
