

py_library(
    name = "__init__",
    srcs = ["__init__.py"],
    deps = [
        ":z_range",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "z_range",
    srcs = ["z_range.py"],
    visibility = ["//visibility:public"],
)

